version: '3.7'

services:
  mongodb:
    image: mongo:6.0.6
    container_name: mongodb
    ports:
      - "27077:27017"
    volumes:
      - /data/db
    restart: always

  app_node:
    container_name: app_node
    build: 
      context: ./web-app/servers
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 5555:5000
    volumes:
      - ./web-app/servers/.env:/web-app/servers/.env
      - ./web-app/servers:/web-app/servers
      - /web-app/servers/node_modules
      
  app_react:
    container_name: app_react
    build:
      context: ./web-app/client
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 9000:3000
    volumes:
      - ./web-app/client:/web-app/client
      - /web-app/client/node_modules
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
